id: node.board_game.default
uuid: 9559ad39-5aba-4667-8200-d10ce3b726e6
targetEntityType: node
bundle: board_game
mode: default
content:
  title:
    type: string
    weight: 0
    settings:
      size: '60'
      placeholder: ''
  body:
    type: text_textarea_with_summary
    weight: 1
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
  field_image:
    type: image_image
    weight: 2
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
  field_release_date:
    type: datetime_default
    weight: 3
    settings: {  }
  field_player_num:
    type: number
    weight: 4
    settings:
      placeholder: ''
  field_play_time:
    type: text_textfield
    weight: 5
    settings:
      size: 60
      placeholder: ''
  field_person:
    type: entity_reference_autocomplete
    weight: 6
    settings:
      match_operator: CONTAINS
      size: 60
      autocomplete_type: single
      placeholder: ''
  field_publisher:
    type: entity_reference_autocomplete
    weight: 7
    settings:
      match_operator: CONTAINS
      size: 60
      autocomplete_type: single
      placeholder: ''
  field_genre:
    type: entity_reference_autocomplete
    weight: 8
    settings:
      match_operator: CONTAINS
      size: 60
      autocomplete_type: single
      placeholder: ''
  field_tags:
    type: taxonomy_autocomplete
    weight: 9
    settings:
      size: 60
      autocomplete_route_name: taxonomy.autocomplete
      placeholder: ''
hidden:
  field_designer: true
status: true
