id: node.game_list.default
uuid: efa5bb64-021a-4de4-b350-80eb05d3d3da
targetEntityType: node
bundle: game_list
mode: default
content:
  title:
    type: string
    weight: -5
    settings:
      size: '60'
      placeholder: ''
  body:
    type: text_textarea_with_summary
    weight: -4
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
  field_games:
    weight: -3
    settings:
      match_operator: CONTAINS
      size: 60
      autocomplete_type: single
      placeholder: ''
    type: entity_reference_autocomplete
hidden: {  }
status: true
