id: node.video_game.default
uuid: 352c9800-f31b-426f-b054-84c7dfc1464a
targetEntityType: node
bundle: video_game
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: -4
    settings: {  }
  field_platform:
    weight: -3
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_developer:
    weight: -2
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_publisher:
    weight: -1
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_genre:
    weight: 0
    label: above
    settings:
      link: true
    type: entity_reference_label
  field_release_date:
    weight: 1
    label: above
    settings:
      format_type: medium
    type: datetime_default
  field_image:
    weight: 2
    label: above
    settings:
      image_style: ''
      image_link: ''
    type: image
  field_website:
    weight: 3
    label: above
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    type: link
  field_tags:
    weight: 4
    label: above
    settings: {  }
    type: taxonomy_term_reference_link
hidden:
  langcode: true
status: true
