id: node.field_logo
uuid: 57220fad-5943-4294-be00-cbcf8a259491
status: true
langcode: en
name: field_logo
entity_type: node
type: image
settings:
  uri_scheme: public
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
  target_type: file
  column_groups:
    file:
      label: File
      columns:
        - target_id
        - width
        - height
    alt:
      label: Alt
      translatable: true
    title:
      label: Title
      translatable: true
module: image
locked: false
cardinality: 1
translatable: false
indexes: {  }
