id: node.board_game.field_play_time
status: true
langcode: en
field_name: field_play_time
entity_type: node
bundle: board_game
label: 'Playing time'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  text_processing: 0
field_type: text
