id: node.video_game.field_website
status: true
langcode: en
field_name: field_website
entity_type: node
bundle: video_game
label: Websites
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  title: '1'
field_type: link
