id: node.board_game.field_player_num
status: true
langcode: en
field_name: field_player_num
entity_type: node
bundle: board_game
label: 'Number of players'
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  min: 1
  max: null
  prefix: ''
  suffix: ''
field_type: integer
