id: node.game_list.field_games
status: true
langcode: en
field_name: field_games
entity_type: node
bundle: game_list
label: Games
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  handler: default
  handler_settings:
    target_bundles:
      board_game: board_game
      video_game: video_game
    sort:
      field: _none
field_type: entity_reference
