id: node.video_game.field_image
status: true
langcode: en
field_name: field_image
entity_type: node
bundle: video_game
label: Image
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  file_directory: image
  file_extensions: 'png gif jpg jpeg'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: false
  alt_field_required: false
  title_field: false
  title_field_required: false
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
field_type: image
