id: administrator
label: Administrator
weight: 2
permissions:
  - 'administer blocks'
  - 'synchronize configuration'
  - 'export configuration'
  - 'import configuration'
  - 'access contextual links'
  - 'administer display modes'
  - 'administer node fields'
  - 'administer node form display'
  - 'administer node display'
  - 'administer taxonomy_term fields'
  - 'administer taxonomy_term form display'
  - 'administer taxonomy_term display'
  - 'administer user fields'
  - 'administer user form display'
  - 'administer user display'
  - 'access files overview'
  - 'administer filters'
  - 'use text format basic_html'
  - 'use text format restricted_html'
  - 'use text format full_html'
  - 'administer image styles'
  - 'administer menu'
  - 'bypass node access'
  - 'administer content types'
  - 'administer nodes'
  - 'access content overview'
  - 'access content'
  - 'view own unpublished content'
  - 'view all revisions'
  - 'revert all revisions'
  - 'delete all revisions'
  - 'create board_game content'
  - 'edit own board_game content'
  - 'edit any board_game content'
  - 'delete own board_game content'
  - 'delete any board_game content'
  - 'view board_game revisions'
  - 'revert board_game revisions'
  - 'delete board_game revisions'
  - 'create developer content'
  - 'edit own developer content'
  - 'edit any developer content'
  - 'delete own developer content'
  - 'delete any developer content'
  - 'view developer revisions'
  - 'revert developer revisions'
  - 'delete developer revisions'
  - 'create game_list content'
  - 'edit own game_list content'
  - 'edit any game_list content'
  - 'delete own game_list content'
  - 'delete any game_list content'
  - 'view game_list revisions'
  - 'revert game_list revisions'
  - 'delete game_list revisions'
  - 'create genre content'
  - 'edit own genre content'
  - 'edit any genre content'
  - 'delete own genre content'
  - 'delete any genre content'
  - 'view genre revisions'
  - 'revert genre revisions'
  - 'delete genre revisions'
  - 'create person content'
  - 'edit own person content'
  - 'edit any person content'
  - 'delete own person content'
  - 'delete any person content'
  - 'view person revisions'
  - 'revert person revisions'
  - 'delete person revisions'
  - 'create platform content'
  - 'edit own platform content'
  - 'edit any platform content'
  - 'delete own platform content'
  - 'delete any platform content'
  - 'view platform revisions'
  - 'revert platform revisions'
  - 'delete platform revisions'
  - 'create publisher content'
  - 'edit own publisher content'
  - 'edit any publisher content'
  - 'delete own publisher content'
  - 'delete any publisher content'
  - 'view publisher revisions'
  - 'revert publisher revisions'
  - 'delete publisher revisions'
  - 'create video_game content'
  - 'edit own video_game content'
  - 'edit any video_game content'
  - 'delete own video_game content'
  - 'delete any video_game content'
  - 'view video_game revisions'
  - 'revert video_game revisions'
  - 'delete video_game revisions'
  - 'restful get entity:node'
  - 'restful post entity:node'
  - 'restful delete entity:node'
  - 'restful patch entity:node'
  - 'administer shortcuts'
  - 'customize shortcut links'
  - 'switch shortcut sets'
  - 'administer modules'
  - 'administer site configuration'
  - 'administer themes'
  - 'administer software updates'
  - 'access administration pages'
  - 'access site in maintenance mode'
  - 'view the administration theme'
  - 'access site reports'
  - 'administer taxonomy'
  - 'edit terms in tags'
  - 'delete terms in tags'
  - 'access toolbar'
  - 'administer permissions'
  - 'administer account settings'
  - 'administer users'
  - 'access user profiles'
  - 'change own username'
  - 'cancel account'
  - 'select account cancellation method'
  - 'administer views'
  - 'access all views'
  - 'administer unit tests'
status: true
uuid: 406000e6-8595-4fc8-975e-9416ea7149bf
langcode: en
